name: Auto cut release branch

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      slack_webhook_ces_engineering_team_url:
        required: false
      slack_webhook_ces_release_prod_url:
        required: false

jobs:
  auto-cut-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commit and push repo yaml
        run: |
          VERSION="release_$(date '+%Y_%U')"
          git checkout -b "$VERSION"
          echo "$VERSION"
          git push --set-upstream origin "$VERSION"

      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          repository: coexservices/workflows
          path: ./workflows


      - name: Send msg to slack
        run: |
          if [ ! -z "${{ secrets.slack_webhook_ces_release_prod_url }}" ]
          then
            echo "Sending slack message ;)"
            workflows/.github/scripts/slack-cut-release-branch-msg.sh "${{ github.repository }}" "${{ secrets.slack_webhook_ces_release_prod_url }}"
          elif [ ! -z "${{ secrets.slack_webhook_ces_engineering_team_url }}" ]
          then
            echo "Sending slack message to engineering channel. Consider switching your secrets to 'inherit'"
            workflows/.github/scripts/slack-cut-release-branch-msg.sh "${{ github.repository }}" "${{ secrets.slack_webhook_ces_engineering_team_url }}"
          else
            echo "Skipping slack message. Have you thought about adding the secret to your build ?"
          fi
